from __future__ import annotations

import json
from pathlib import Path
from typing import Any

VENDOR_MAPPER_FN: dict[str, str] = {
    "cvent": "mapCventToMaster",
    "givecampus": "mapGiveCampusToMaster",
}

VENDOR_MAPPER_MODULE: dict[str, str] = {
    "cvent": "../../src/mappers/cvent.js",
    "givecampus": "../../src/mappers/givecampus.js",
}


def count_validation_issues(validation_errors: dict[str, Any]) -> int:
    field_errors = validation_errors.get("fieldErrors", {})
    form_errors = validation_errors.get("formErrors", [])
    return sum(len(values) for values in field_errors.values()) + len(form_errors)


def build_drift_test_source(
    vendor: str,
    basename: str,
    captured_at: str,
    issue_count: int,
) -> str:
    mapper_fn = VENDOR_MAPPER_FN[vendor]
    mapper_module = VENDOR_MAPPER_MODULE[vendor]
    fixture_import_path = f"../__fixtures__/drift/{basename}.json"

    return f"""/**
 * AUTO-GENERATED by Drift Agent Runner — do not edit manually.
 * Captured at: {captured_at}
 * Vendor: {vendor}
 * Validation issues: {issue_count}
 */
import {{ describe, expect, it }} from 'vitest'

import {{ ConstituentEventSchema }} from '../../src/schema/master.js'
import {{ {mapper_fn} }} from '{mapper_module}'
import driftPayload from '{fixture_import_path}'

describe('schema drift: {vendor} ({basename})', () => {{
  it('maps captured production payload to ConstituentEvent', () => {{
    const result = {mapper_fn}(driftPayload)

    expect(ConstituentEventSchema.safeParse(result).success).toBe(true)
  }})
}})
"""


def write_drift_artifacts(
    *,
    repo_root: Path,
    basename: str,
    vendor: str,
    raw_payload: Any,
    captured_at: str,
    issue_count: int,
    dry_run: bool,
) -> tuple[Path, Path]:
    fixture_path = repo_root / "tests" / "__fixtures__" / "drift" / f"{basename}.json"
    test_path = repo_root / "tests" / "autogenerated" / f"{basename}.test.ts"

    if dry_run:
        return fixture_path, test_path

    fixture_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.parent.mkdir(parents=True, exist_ok=True)

    fixture_path.write_text(f"{json.dumps(raw_payload, indent=2)}\n", encoding="utf-8")
    test_path.write_text(
        build_drift_test_source(vendor, basename, captured_at, issue_count),
        encoding="utf-8",
    )

    return fixture_path, test_path
