import { chmod, readFile, rm } from 'node:fs/promises'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ZodError } from 'zod'

import {
  buildDriftBasename,
  buildDriftFixtureRelativePath,
  buildDriftTestRelativePath,
  buildDriftTestSource,
  captureSchemaDrift,
  formatDriftTimestamp,
  isDriftCaptureEnabled,
  isDriftVendor,
  isReadOnlyFilesystemError,
} from '../src/utils/driftCapture.js'

const sampleZodError = new ZodError([
  {
    code: 'invalid_type',
    expected: 'string',
    path: ['EmailAddress'],
    message: 'Invalid input: expected string, received undefined',
  },
])

const PROJECT_ROOT = path.resolve(import.meta.dirname, '..')

describe('drift capture helpers', () => {
  it('formats timestamps for filesystem-safe basenames', () => {
    const formatted = formatDriftTimestamp(new Date('2026-06-20T15:04:05.123Z'))

    expect(formatted).toBe('2026-06-20T15-04-05-123Z')
  })

  it('builds deterministic artifact paths from vendor and timestamp', () => {
    const basename = buildDriftBasename('cvent', '2026-06-20T15-04-05-123Z')

    expect(basename).toBe('cvent-2026-06-20T15-04-05-123Z')
    expect(buildDriftFixtureRelativePath(basename)).toBe(
      'tests/__fixtures__/drift/cvent-2026-06-20T15-04-05-123Z.json',
    )
    expect(buildDriftTestRelativePath(basename)).toBe(
      'tests/autogenerated/cvent-2026-06-20T15-04-05-123Z.test.ts',
    )
  })

  it('narrows supported drift vendors', () => {
    expect(isDriftVendor('cvent')).toBe(true)
    expect(isDriftVendor('givecampus')).toBe(true)
    expect(isDriftVendor('unknown')).toBe(false)
  })

  it('generates mapper-specific failing Vitest sources', () => {
    const cventSource = buildDriftTestSource(
      'cvent',
      'cvent-2026-06-20T15-04-05-123Z',
      '2026-06-20T15:04:05.123Z',
      2,
    )
    const giveCampusSource = buildDriftTestSource(
      'givecampus',
      'givecampus-2026-06-20T15-04-05-123Z',
      '2026-06-20T15:04:05.123Z',
      1,
    )

    expect(cventSource).toContain("import { mapCventToMaster } from '../../src/mappers/cvent.js'")
    expect(cventSource).toContain('ConstituentEventSchema.safeParse(result).success')
    expect(giveCampusSource).toContain(
      "import { mapGiveCampusToMaster } from '../../src/mappers/givecampus.js'",
    )
  })

  it('detects read-only filesystem errors', () => {
    expect(
      isReadOnlyFilesystemError(
        Object.assign(new Error('read-only file system'), { code: 'EROFS' }),
      ),
    ).toBe(true)
    expect(
      isReadOnlyFilesystemError(Object.assign(new Error('permission denied'), { code: 'EACCES' })),
    ).toBe(true)
    expect(
      isReadOnlyFilesystemError(Object.assign(new Error('not permitted'), { code: 'EPERM' })),
    ).toBe(true)
  })
})

describe('captureSchemaDrift', () => {
  const originalVitest = process.env.VITEST
  const originalDriftCapture = process.env.DRIFT_CAPTURE
  const createdArtifacts: string[] = []

  beforeEach(() => {
    process.env.VITEST = 'false'
    delete process.env.DRIFT_CAPTURE
    createdArtifacts.length = 0
  })

  afterEach(async () => {
    process.env.VITEST = originalVitest

    if (originalDriftCapture === undefined) {
      delete process.env.DRIFT_CAPTURE
    } else {
      process.env.DRIFT_CAPTURE = originalDriftCapture
    }

    await Promise.all(
      createdArtifacts.map((artifactPath) => rm(artifactPath, { force: true })),
    )
  })

  it('is disabled while Vitest is running by default', () => {
    process.env.VITEST = 'true'

    expect(isDriftCaptureEnabled()).toBe(false)
  })

  it('returns disabled when drift capture is turned off', async () => {
    process.env.DRIFT_CAPTURE = 'disabled'

    const result = await captureSchemaDrift('cvent', { invalid: true }, sampleZodError)

    expect(result).toEqual({ captured: false, reason: 'disabled' })
  })

  it('returns invalid_vendor for unsupported vendors', async () => {
    const result = await captureSchemaDrift('unknown', { invalid: true }, sampleZodError)

    expect(result).toEqual({ captured: false, reason: 'invalid_vendor' })
  })

  it('writes fixture and autogenerated test files in Node environments', async () => {
    const basename = 'cvent-2026-06-20T15-04-05-123Z'
    const rawPayload = {
      AttendeeStub: 'attendee-12345',
      EventCode: 'REG-2026-GALA',
    }
    const fixturePath = path.join(PROJECT_ROOT, buildDriftFixtureRelativePath(basename))
    const testPath = path.join(PROJECT_ROOT, buildDriftTestRelativePath(basename))

    createdArtifacts.push(fixturePath, testPath)

    vi.spyOn(Date.prototype, 'toISOString').mockReturnValue('2026-06-20T15:04:05.123Z')

    const result = await captureSchemaDrift('cvent', rawPayload, sampleZodError)

    expect(result).toEqual({
      captured: true,
      fixturePath,
      testPath,
      basename,
    })

    const savedFixture = await readFile(fixturePath, 'utf8')
    const savedTest = await readFile(testPath, 'utf8')

    expect(JSON.parse(savedFixture)).toEqual(rawPayload)
    expect(savedTest).toContain('mapCventToMaster(driftPayload)')

    vi.restoreAllMocks()
  })

  it('returns write_error when drift artifacts already exist', async () => {
    const basename = 'givecampus-2026-06-20T15-04-05-456Z'
    const fixturePath = path.join(PROJECT_ROOT, buildDriftFixtureRelativePath(basename))
    const testPath = path.join(PROJECT_ROOT, buildDriftTestRelativePath(basename))

    createdArtifacts.push(fixturePath, testPath)

    vi.spyOn(Date.prototype, 'toISOString').mockReturnValue('2026-06-20T15:04:05.456Z')

    const firstResult = await captureSchemaDrift('givecampus', { id: 'gc-1' }, sampleZodError)
    const secondResult = await captureSchemaDrift('givecampus', { id: 'gc-1' }, sampleZodError)

    expect(firstResult.captured).toBe(true)
    expect(secondResult).toMatchObject({
      captured: false,
      reason: 'write_error',
    })

    vi.restoreAllMocks()
  })

  it('returns read_only when the drift directory is not writable', async () => {
    const driftDir = path.join(PROJECT_ROOT, 'tests/__fixtures__/drift')
    const basename = 'cvent-2026-06-20T15-04-05-789Z'
    const fixturePath = path.join(PROJECT_ROOT, buildDriftFixtureRelativePath(basename))
    const testPath = path.join(PROJECT_ROOT, buildDriftTestRelativePath(basename))

    createdArtifacts.push(fixturePath, testPath)

    vi.spyOn(Date.prototype, 'toISOString').mockReturnValue('2026-06-20T15:04:05.789Z')

    await chmod(driftDir, 0o555)

    try {
      const result = await captureSchemaDrift('cvent', { AttendeeStub: 'x' }, sampleZodError)

      expect(result).toMatchObject({
        captured: false,
        reason: 'read_only',
      })
    } finally {
      await chmod(driftDir, 0o755)
      vi.restoreAllMocks()
    }
  })
})
