import type { ZodError } from 'zod'

import type { MappingArtifact } from '../schema/mapping.js'
import { enqueueDriftEvent, listDriftEvents, type DriftMapperKind } from '../store/driftQueue.js'

export const DRIFT_VENDORS = [
  'cvent',
  'givecampus',
  'imodules',
  'blackbaud',
  'npsp',
  'slate',
  'ellucian',
] as const

export type DriftVendor = (typeof DRIFT_VENDORS)[number]

type DriftVendorConfig = {
  readonly mapperFn:
    | 'mapCventToMaster'
    | 'mapGiveCampusToMaster'
    | 'mapImodulesToMaster'
    | 'mapBlackbaudToMaster'
    | 'mapNpspToMaster'
    | 'mapSlateToMaster'
    | 'mapEllucianToMaster'
  readonly mapperModule:
    | '../../src/mappers/cvent.js'
    | '../../src/mappers/givecampus.js'
    | '../../src/mappers/imodules.js'
    | '../../src/mappers/blackbaud.js'
    | '../../src/mappers/npsp.js'
    | '../../src/mappers/slate.js'
    | '../../src/mappers/ellucian.js'
}

const VENDOR_DRIFT_CONFIG: Record<DriftVendor, DriftVendorConfig> = {
  cvent: {
    mapperFn: 'mapCventToMaster',
    mapperModule: '../../src/mappers/cvent.js',
  },
  givecampus: {
    mapperFn: 'mapGiveCampusToMaster',
    mapperModule: '../../src/mappers/givecampus.js',
  },
  imodules: {
    mapperFn: 'mapImodulesToMaster',
    mapperModule: '../../src/mappers/imodules.js',
  },
  blackbaud: {
    mapperFn: 'mapBlackbaudToMaster',
    mapperModule: '../../src/mappers/blackbaud.js',
  },
  npsp: {
    mapperFn: 'mapNpspToMaster',
    mapperModule: '../../src/mappers/npsp.js',
  },
  slate: {
    mapperFn: 'mapSlateToMaster',
    mapperModule: '../../src/mappers/slate.js',
  },
  ellucian: {
    mapperFn: 'mapEllucianToMaster',
    mapperModule: '../../src/mappers/ellucian.js',
  },
}

export type DriftCaptureFailureReason = 'disabled' | 'invalid_vendor'

export type DriftCaptureResult =
  | {
      captured: true
      driftEventId: string
      basename: string
    }
  | {
      captured: false
      reason: DriftCaptureFailureReason
    }

export function isDriftVendor(value: string): value is DriftVendor {
  return (DRIFT_VENDORS as readonly string[]).includes(value)
}

export function isDriftCaptureEnabled(): boolean {
  if (process.env.DRIFT_CAPTURE === 'disabled') {
    return false
  }

  return true
}

/** Filesystem-safe, deterministic formatting for a given instant. */
export function formatDriftTimestamp(date: Date): string {
  return date.toISOString().replace(/[:.]/g, '-')
}

export function buildDriftBasename(vendor: DriftVendor, timestamp: string): string {
  return `${vendor}-${timestamp}`
}

export function buildDriftFixtureRelativePath(basename: string): string {
  return `tests/__fixtures__/drift/${basename}.json`
}

export function buildDriftTestRelativePath(basename: string): string {
  return `tests/autogenerated/${basename}.test.ts`
}

/**
 * Generates Vitest source for CI workers (GitHub Actions / Airflow) that pull
 * pending drift events from the database queue.
 */
export function buildDriftTestSource(
  vendor: DriftVendor,
  basename: string,
  capturedAtIso: string,
  issueCount: number,
  options?: {
    mapperKind?: DriftMapperKind
    mappingArtifact?: MappingArtifact
  },
): string {
  const fixtureImportPath = `../__fixtures__/drift/${basename}.json`

  if (options?.mapperKind === 'dynamic' && options.mappingArtifact) {
    const artifactJson = JSON.stringify(options.mappingArtifact, null, 2)

    return `/**
 * AUTO-GENERATED by Drift Capture Engine — do not edit manually.
 * Captured at: ${capturedAtIso}
 * Vendor: ${vendor}
 * Mapper: dynamic (admin canvas)
 * Validation issues: ${issueCount}
 */
import { describe, expect, it } from 'vitest'

import { mapWithArtifact } from '../../src/mappers/dynamic.js'
import { ConstituentEventSchema } from '../../src/schema/master.js'
import type { MappingArtifact } from '../../src/schema/mapping.js'
import driftPayload from '${fixtureImportPath}'

const mappingArtifact = ${artifactJson} as MappingArtifact

describe('schema drift: ${vendor} (${basename}) [dynamic]', () => {
  it('maps captured production payload via admin canvas artifact', () => {
    const result = mapWithArtifact(driftPayload, mappingArtifact)

    expect(ConstituentEventSchema.safeParse(result).success).toBe(true)
  })
})
`
  }

  const config = VENDOR_DRIFT_CONFIG[vendor]

  return `/**
 * AUTO-GENERATED by Drift Capture Engine — do not edit manually.
 * Captured at: ${capturedAtIso}
 * Vendor: ${vendor}
 * Validation issues: ${issueCount}
 */
import { describe, expect, it } from 'vitest'

import { ConstituentEventSchema } from '../../src/schema/master.js'
import { ${config.mapperFn} } from '${config.mapperModule}'
import driftPayload from '${fixtureImportPath}'

describe('schema drift: ${vendor} (${basename})', () => {
  it('maps captured production payload to ConstituentEvent', () => {
    const result = ${config.mapperFn}(driftPayload)

    expect(ConstituentEventSchema.safeParse(result).success).toBe(true)
  })
})
`
}

/**
 * Enqueues a failed vendor payload to the drift dead-letter store.
 * Dynamic test generation and Git commits are handled by isolated CI workers.
 */
export async function captureSchemaDrift(
  vendor: string,
  rawPayload: unknown,
  validationError: ZodError,
  options?: {
    mapperKind?: DriftMapperKind
    mappingArtifact?: MappingArtifact
  },
): Promise<DriftCaptureResult> {
  if (!isDriftCaptureEnabled()) {
    return { captured: false, reason: 'disabled' }
  }

  if (!isDriftVendor(vendor)) {
    return { captured: false, reason: 'invalid_vendor' }
  }

  const capturedAt = new Date()
  const timestamp = formatDriftTimestamp(capturedAt)
  const basename = buildDriftBasename(vendor, timestamp)

  const driftEvent = await enqueueDriftEvent(vendor, rawPayload, validationError, {
    mapperKind: options?.mapperKind ?? 'builtin',
    mappingArtifact: options?.mappingArtifact,
  })

  return {
    captured: true,
    driftEventId: driftEvent.id,
    basename,
  }
}

export async function countPendingDriftEvents(): Promise<number> {
  const events = await listDriftEvents(undefined, 1000, 'pending')
  return events.length
}
