import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import type { ZodError } from 'zod'

import { enqueueDriftEvent } from '../store/driftQueue.js'

export const DRIFT_VENDORS = ['cvent', 'givecampus'] as const

export type DriftVendor = (typeof DRIFT_VENDORS)[number]

type DriftVendorConfig = {
  readonly mapperFn: 'mapCventToMaster' | 'mapGiveCampusToMaster'
  readonly mapperModule: '../../src/mappers/cvent.js' | '../../src/mappers/givecampus.js'
}

const VENDOR_DRIFT_CONFIG: Record<DriftVendor, DriftVendorConfig> = {
  cvent: {
    mapperFn: 'mapCventToMaster',
    mapperModule: '../../src/mappers/cvent.js',
  },
  givecampus: {
    mapperFn: 'mapGiveCampusToMaster',
    mapperModule: '../../src/mappers/givecampus.js',
  },
}

export type DriftCaptureFailureReason = 'disabled' | 'invalid_vendor'

export type DriftCaptureResult =
  | {
      captured: true
      driftEventId: string
      fixturePath?: string
      testPath?: string
      basename?: string
      localWriteSkipped?: boolean
    }
  | {
      captured: false
      reason: DriftCaptureFailureReason
    }

const PROJECT_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..',
)

export function isDriftVendor(value: string): value is DriftVendor {
  return (DRIFT_VENDORS as readonly string[]).includes(value)
}

export function isDriftCaptureEnabled(): boolean {
  if (process.env.DRIFT_CAPTURE === 'disabled') {
    return false
  }

  return true
}

export function isLocalFilesystemCaptureEnabled(): boolean {
  if (!isDriftCaptureEnabled()) {
    return false
  }

  if (process.env.VITEST === 'true') {
    return false
  }

  return process.env.DRIFT_CAPTURE !== 'queue-only'
}

/** Filesystem-safe, deterministic formatting for a given instant. */
export function formatDriftTimestamp(date: Date): string {
  return date.toISOString().replace(/[:.]/g, '-')
}

export function buildDriftBasename(vendor: DriftVendor, timestamp: string): string {
  return `${vendor}-${timestamp}`
}

export function buildDriftFixtureRelativePath(basename: string): string {
  return path.join('tests', '__fixtures__', 'drift', `${basename}.json`)
}

export function buildDriftTestRelativePath(basename: string): string {
  return path.join('tests', 'autogenerated', `${basename}.test.ts`)
}

export function buildDriftTestSource(
  vendor: DriftVendor,
  basename: string,
  capturedAtIso: string,
  issueCount: number,
): string {
  const config = VENDOR_DRIFT_CONFIG[vendor]
  const fixtureImportPath = `../__fixtures__/drift/${basename}.json`

  return `/**
 * AUTO-GENERATED by Drift Capture Engine — do not edit manually.
 * Captured at: ${capturedAtIso}
 * Vendor: ${vendor}
 * Validation issues: ${issueCount}
 */
import { describe, expect, it } from 'vitest'

import { ConstituentEventSchema } from '../../src/schema/master.js'
import { ${config.mapperFn} } from '${config.mapperModule}'
import driftPayload from '${fixtureImportPath}'

describe('schema drift: ${vendor} (${basename})', () => {
  it('maps captured production payload to ConstituentEvent', () => {
    const result = ${config.mapperFn}(driftPayload)

    expect(ConstituentEventSchema.safeParse(result).success).toBe(true)
  })
})
`
}

export function isReadOnlyFilesystemError(error: unknown): boolean {
  if (!(error instanceof Error) || !('code' in error)) {
    return false
  }

  const code = (error as NodeJS.ErrnoException).code

  return code === 'EROFS' || code === 'EPERM' || code === 'EACCES'
}

async function writeLocalDriftArtifacts(
  fixturePath: string,
  testPath: string,
  rawPayload: unknown,
  testSource: string,
): Promise<{ fixturePath?: string; testPath?: string; basename?: string; skipped?: boolean; error?: string }> {
  if (!isLocalFilesystemCaptureEnabled()) {
    return { skipped: true }
  }

  try {
    await mkdir(path.dirname(fixturePath), { recursive: true })
    await mkdir(path.dirname(testPath), { recursive: true })

    await writeFile(fixturePath, `${JSON.stringify(rawPayload, null, 2)}\n`, {
      encoding: 'utf8',
      flag: 'wx',
    })

    await writeFile(testPath, testSource, {
      encoding: 'utf8',
      flag: 'wx',
    })

    return {
      fixturePath,
      testPath,
      basename: path.basename(fixturePath, '.json'),
    }
  } catch (error) {
    return { error: error instanceof Error ? error.message : String(error) }
  }
}

/**
 * Enqueues a failed vendor payload to the drift dead-letter store and,
 * when enabled, generates local Vitest fixtures for the agent loop.
 */
export async function captureSchemaDrift(
  vendor: string,
  rawPayload: unknown,
  validationError: ZodError,
): Promise<DriftCaptureResult> {
  if (!isDriftCaptureEnabled()) {
    return { captured: false, reason: 'disabled' }
  }

  if (!isDriftVendor(vendor)) {
    return { captured: false, reason: 'invalid_vendor' }
  }

  const capturedAt = new Date()
  const timestamp = formatDriftTimestamp(capturedAt)
  const basename = buildDriftBasename(vendor, timestamp)
  const fixturePath = path.join(PROJECT_ROOT, buildDriftFixtureRelativePath(basename))
  const testPath = path.join(PROJECT_ROOT, buildDriftTestRelativePath(basename))
  const testSource = buildDriftTestSource(
    vendor,
    basename,
    capturedAt.toISOString(),
    validationError.issues.length,
  )

  const localArtifacts = await writeLocalDriftArtifacts(
    fixturePath,
    testPath,
    rawPayload,
    testSource,
  )

  const driftEvent = enqueueDriftEvent(vendor, rawPayload, validationError, {
    fixturePath: localArtifacts.fixturePath,
    testPath: localArtifacts.testPath,
  })

  if (localArtifacts.error) {
    console.warn('[drift-capture] local fixture write failed; dead-letter queue persisted event', {
      vendor,
      driftEventId: driftEvent.id,
      error: localArtifacts.error,
    })
  }

  return {
    captured: true,
    driftEventId: driftEvent.id,
    fixturePath: localArtifacts.fixturePath,
    testPath: localArtifacts.testPath,
    basename: localArtifacts.basename,
    localWriteSkipped: localArtifacts.skipped,
  }
}
