import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import type { ZodError } from 'zod'

export const DRIFT_VENDORS = ['cvent', 'givecampus'] as const

export type DriftVendor = (typeof DRIFT_VENDORS)[number]

type DriftVendorConfig = {
  readonly mapperFn: 'mapCventToMaster' | 'mapGiveCampusToMaster'
  readonly mapperModule: '../../src/mappers/cvent.js' | '../../src/mappers/givecampus.js'
}

const VENDOR_DRIFT_CONFIG: Record<DriftVendor, DriftVendorConfig> = {
  cvent: {
    mapperFn: 'mapCventToMaster',
    mapperModule: '../../src/mappers/cvent.js',
  },
  givecampus: {
    mapperFn: 'mapGiveCampusToMaster',
    mapperModule: '../../src/mappers/givecampus.js',
  },
}

export type DriftCaptureFailureReason =
  | 'disabled'
  | 'invalid_vendor'
  | 'read_only'
  | 'write_error'

export type DriftCaptureResult =
  | {
      captured: true
      fixturePath: string
      testPath: string
      basename: string
    }
  | {
      captured: false
      reason: DriftCaptureFailureReason
      error?: string
    }

const PROJECT_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..',
)

export function isDriftVendor(value: string): value is DriftVendor {
  return (DRIFT_VENDORS as readonly string[]).includes(value)
}

export function isDriftCaptureEnabled(): boolean {
  if (typeof process === 'undefined' || process.versions.node === undefined) {
    return false
  }

  if (process.env.VITEST === 'true') {
    return false
  }

  if (process.env.DRIFT_CAPTURE === 'disabled') {
    return false
  }

  return true
}

/** Filesystem-safe, deterministic formatting for a given instant. */
export function formatDriftTimestamp(date: Date): string {
  return date.toISOString().replace(/[:.]/g, '-')
}

export function buildDriftBasename(vendor: DriftVendor, timestamp: string): string {
  return `${vendor}-${timestamp}`
}

export function buildDriftFixtureRelativePath(basename: string): string {
  return path.join('tests', '__fixtures__', 'drift', `${basename}.json`)
}

export function buildDriftTestRelativePath(basename: string): string {
  return path.join('tests', 'autogenerated', `${basename}.test.ts`)
}

export function buildDriftTestSource(
  vendor: DriftVendor,
  basename: string,
  capturedAtIso: string,
  issueCount: number,
): string {
  const config = VENDOR_DRIFT_CONFIG[vendor]
  const fixtureImportPath = `../__fixtures__/drift/${basename}.json`

  return `/**
 * AUTO-GENERATED by Drift Capture Engine — do not edit manually.
 * Captured at: ${capturedAtIso}
 * Vendor: ${vendor}
 * Validation issues: ${issueCount}
 */
import { describe, expect, it } from 'vitest'

import { ConstituentEventSchema } from '../../src/schema/master.js'
import { ${config.mapperFn} } from '${config.mapperModule}'
import driftPayload from '${fixtureImportPath}'

describe('schema drift: ${vendor} (${basename})', () => {
  it('maps captured production payload to ConstituentEvent', () => {
    const result = ${config.mapperFn}(driftPayload)

    expect(ConstituentEventSchema.safeParse(result).success).toBe(true)
  })
})
`
}

export function isReadOnlyFilesystemError(error: unknown): boolean {
  if (!(error instanceof Error) || !('code' in error)) {
    return false
  }

  const code = (error as NodeJS.ErrnoException).code

  return code === 'EROFS' || code === 'EPERM' || code === 'EACCES'
}

async function writeDriftArtifacts(
  fixturePath: string,
  testPath: string,
  rawPayload: unknown,
  testSource: string,
): Promise<DriftCaptureResult> {
  try {
    await mkdir(path.dirname(fixturePath), { recursive: true })
    await mkdir(path.dirname(testPath), { recursive: true })

    await writeFile(fixturePath, `${JSON.stringify(rawPayload, null, 2)}\n`, {
      encoding: 'utf8',
      flag: 'wx',
    })

    await writeFile(testPath, testSource, {
      encoding: 'utf8',
      flag: 'wx',
    })

    return {
      captured: true,
      fixturePath,
      testPath,
      basename: path.basename(fixturePath, '.json'),
    }
  } catch (error) {
    if (isReadOnlyFilesystemError(error)) {
      return {
        captured: false,
        reason: 'read_only',
        error: error instanceof Error ? error.message : String(error),
      }
    }

    return {
      captured: false,
      reason: 'write_error',
      error: error instanceof Error ? error.message : String(error),
    }
  }
}

/**
 * Persists a failed vendor payload and generates a failing Vitest contract
 * so an autonomous agent can patch the mapper when upstream schemas drift.
 */
export async function captureSchemaDrift(
  vendor: string,
  rawPayload: unknown,
  validationError: ZodError,
): Promise<DriftCaptureResult> {
  if (!isDriftCaptureEnabled()) {
    return { captured: false, reason: 'disabled' }
  }

  if (!isDriftVendor(vendor)) {
    return { captured: false, reason: 'invalid_vendor' }
  }

  const capturedAt = new Date()
  const timestamp = formatDriftTimestamp(capturedAt)
  const basename = buildDriftBasename(vendor, timestamp)
  const fixturePath = path.join(PROJECT_ROOT, buildDriftFixtureRelativePath(basename))
  const testPath = path.join(PROJECT_ROOT, buildDriftTestRelativePath(basename))
  const testSource = buildDriftTestSource(
    vendor,
    basename,
    capturedAt.toISOString(),
    validationError.issues.length,
  )

  return writeDriftArtifacts(fixturePath, testPath, rawPayload, testSource)
}
