import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { ZodError } from 'zod'

import {
  buildDriftBasename,
  buildDriftFixtureRelativePath,
  buildDriftTestRelativePath,
  buildDriftTestSource,
  captureSchemaDrift,
  formatDriftTimestamp,
  isDriftCaptureEnabled,
  isDriftVendor,
} from '../../src/utils/driftCapture.js'
import { clearDriftQueue, listDriftEvents } from '../../src/store/driftQueue.js'

const sampleZodError = new ZodError([
  {
    code: 'invalid_type',
    expected: 'string',
    path: ['EmailAddress'],
    message: 'Invalid input: expected string, received undefined',
  },
])

describe('drift capture helpers', () => {
  it('formats timestamps for filesystem-safe basenames', () => {
    const formatted = formatDriftTimestamp(new Date('2026-06-20T15:04:05.123Z'))

    expect(formatted).toBe('2026-06-20T15-04-05-123Z')
  })

  it('builds deterministic artifact paths from vendor and timestamp', () => {
    const basename = buildDriftBasename('cvent', '2026-06-20T15-04-05-123Z')

    expect(basename).toBe('cvent-2026-06-20T15-04-05-123Z')
    expect(buildDriftFixtureRelativePath(basename)).toBe(
      'tests/__fixtures__/drift/cvent-2026-06-20T15-04-05-123Z.json',
    )
    expect(buildDriftTestRelativePath(basename)).toBe(
      'tests/autogenerated/cvent-2026-06-20T15-04-05-123Z.test.ts',
    )
  })

  it('narrows supported drift vendors', () => {
    expect(isDriftVendor('cvent')).toBe(true)
    expect(isDriftVendor('givecampus')).toBe(true)
    expect(isDriftVendor('unknown')).toBe(false)
  })

  it('generates mapper-specific failing Vitest sources for CI workers', () => {
    const cventSource = buildDriftTestSource(
      'cvent',
      'cvent-2026-06-20T15-04-05-123Z',
      '2026-06-20T15:04:05.123Z',
      2,
    )
    const imodulesSource = buildDriftTestSource(
      'imodules',
      'imodules-2026-06-20T15-04-05-123Z',
      '2026-06-20T15:04:05.123Z',
      1,
    )

    expect(cventSource).toContain("import { mapCventToMaster } from '../../src/mappers/cvent.js'")
    expect(cventSource).toContain('ConstituentEventSchema.safeParse(result).success')
    expect(imodulesSource).toContain("import { mapImodulesToMaster } from '../../src/mappers/imodules.js'")
  })

  it('generates dynamic-mapper Vitest sources when an admin canvas artifact was active', () => {
    const dynamicSource = buildDriftTestSource(
      'givecampus',
      'givecampus-2026-06-20T15-04-05-123Z',
      '2026-06-20T15:04:05.123Z',
      1,
      {
        mapperKind: 'dynamic',
        mappingArtifact: {
          vendor: 'GiveCampus',
          exportedAt: '2026-06-20T12:00:00.000Z',
          mappings: [{ source: 'donor_email', target: 'constituentEmail' }],
          metadataMappings: [],
        },
      },
    )

    expect(dynamicSource).toContain("import { mapWithArtifact } from '../../src/mappers/dynamic.js'")
    expect(dynamicSource).toContain('[dynamic]')
    expect(dynamicSource).toContain('mapWithArtifact(driftPayload, mappingArtifact)')
  })
})

describe('captureSchemaDrift', () => {
  const originalDriftCapture = process.env.DRIFT_CAPTURE

  beforeEach(async () => {
    await clearDriftQueue()
    delete process.env.DRIFT_CAPTURE
  })

  afterEach(() => {
    if (originalDriftCapture === undefined) {
      delete process.env.DRIFT_CAPTURE
    } else {
      process.env.DRIFT_CAPTURE = originalDriftCapture
    }
  })

  it('returns disabled when drift capture is turned off', async () => {
    process.env.DRIFT_CAPTURE = 'disabled'

    const result = await captureSchemaDrift('cvent', { invalid: true }, sampleZodError)

    expect(result).toEqual({ captured: false, reason: 'disabled' })
  })

  it('returns invalid_vendor for unsupported vendors', async () => {
    const result = await captureSchemaDrift('unknown', { invalid: true }, sampleZodError)

    expect(result).toEqual({ captured: false, reason: 'invalid_vendor' })
  })

  it('persists drift events to the database queue without touching the filesystem', async () => {
    vi.spyOn(Date.prototype, 'toISOString').mockReturnValue('2026-06-20T15:04:05.123Z')

    const rawPayload = {
      AttendeeStub: 'attendee-12345',
      EventCode: 'REG-2026-GALA',
    }

    const result = await captureSchemaDrift('cvent', rawPayload, sampleZodError)

    expect(result.captured).toBe(true)
    if (result.captured) {
      expect(result.basename).toBe('cvent-2026-06-20T15-04-05-123Z')
      expect(result.driftEventId).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
      )
    }

    const queued = await listDriftEvents('cvent')
    expect(queued).toHaveLength(1)
    expect(queued[0]?.rawPayload).toEqual(rawPayload)
    expect(isDriftCaptureEnabled()).toBe(true)

    vi.restoreAllMocks()
  })

  it('enqueues multiple drift events for repeated failures', async () => {
    vi.spyOn(Date.prototype, 'toISOString')
      .mockReturnValueOnce('2026-06-20T15:04:05.456Z')
      .mockReturnValueOnce('2026-06-20T15:04:05.789Z')

    const firstResult = await captureSchemaDrift('givecampus', { id: 'gc-1' }, sampleZodError)
    const secondResult = await captureSchemaDrift('givecampus', { id: 'gc-2' }, sampleZodError)

    expect(firstResult.captured).toBe(true)
    expect(secondResult.captured).toBe(true)
    expect(await listDriftEvents('givecampus')).toHaveLength(2)

    vi.restoreAllMocks()
  })

  it('records dynamic mapper context when an admin canvas artifact was active', async () => {
    const artifact = {
      vendor: 'GiveCampus',
      exportedAt: '2026-06-20T12:00:00.000Z',
      mappings: [{ source: 'donor_email', target: 'constituentEmail' as const }],
      metadataMappings: [],
    }

    const result = await captureSchemaDrift(
      'givecampus',
      { id: 'gc-1' },
      sampleZodError,
      { mapperKind: 'dynamic', mappingArtifact: artifact },
    )

    expect(result.captured).toBe(true)

    const queued = await listDriftEvents('givecampus')
    expect(queued[0]?.mapperKind).toBe('dynamic')
    expect(queued[0]?.mappingArtifact).toEqual(artifact)
  })
})
